// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3z3c0dLf1AYGdNSl11j6lhoA9WN6M9OU',
    appId: '1:917706034914:web:8365622a7b5cdde1f498bb',
    messagingSenderId: '917706034914',
    projectId: 'car-rent-app-7139b',
    authDomain: 'car-rent-app-7139b.firebaseapp.com',
    storageBucket: 'car-rent-app-7139b.appspot.com',
    measurementId: 'G-BYECLH81YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAII2T6aIqPkNvhwZQ6my8pV6blZkl5oq8',
    appId: '1:917706034914:android:731e00125340b2ddf498bb',
    messagingSenderId: '917706034914',
    projectId: 'car-rent-app-7139b',
    storageBucket: 'car-rent-app-7139b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUbFKDD8vrmcOftQCf0gw2-EcwEEaTCQ',
    appId: '1:917706034914:ios:b4b1ff6a40fc58a2f498bb',
    messagingSenderId: '917706034914',
    projectId: 'car-rent-app-7139b',
    storageBucket: 'car-rent-app-7139b.appspot.com',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUbFKDD8vrmcOftQCf0gw2-EcwEEaTCQ',
    appId: '1:917706034914:ios:b4b1ff6a40fc58a2f498bb',
    messagingSenderId: '917706034914',
    projectId: 'car-rent-app-7139b',
    storageBucket: 'car-rent-app-7139b.appspot.com',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3z3c0dLf1AYGdNSl11j6lhoA9WN6M9OU',
    appId: '1:917706034914:web:cf5818fb4d69a04af498bb',
    messagingSenderId: '917706034914',
    projectId: 'car-rent-app-7139b',
    authDomain: 'car-rent-app-7139b.firebaseapp.com',
    storageBucket: 'car-rent-app-7139b.appspot.com',
    measurementId: 'G-7MK932M29Y',
  );
}
